In [1]:
import pandas as pd
import numpy as np
from math import fabs, floor
from random import normalvariate, randint

In [4]:
data = pd.DataFrame()

In [6]:
data.columns

Index([], dtype='object')

In [11]:
y = [randint(0, 1) for i in range(Length)]
data['Итог'] = y

In [8]:
Length = 10000

In [14]:
salary = []

for i in range((Length)):
    if y[i] == 1:
        salary.append(fabs(round(normalvariate(100, 50))) * 1000)
    else:
        salary.append(fabs(round(normalvariate(30, 10))) * 1000)
        
data['Зарплата'] = salary

In [58]:
age = []

for i in range(Length):
    if y[i] == 1:
        age.append(fabs(round(normalvariate(45, 10))) )
    else:
        age.append(fabs(round(normalvariate(30, 10))))
        
for i in range(Length):
    if age[i] < 18:
           age[i] += randint(18, 30)
    if age[i] > 60 and y == 1 and summ[i] > 100000:
        age[i] -= randint(10, 30)
        
        
data['Возраст'] = age

In [56]:
summ = []

for i in range(Length):
    if salary[i] > 100000:
        summ.append(fabs(round(normalvariate(500, 100))) * 1000)
    elif salary[i] < 100000 and y[i] == 0:
        summ.append(fabs(round(normalvariate(500, 100))) * 1000)
    else:
        summ.append(fabs(round(normalvariate(200, 50))) * 1000)
    

        
for i in range(Length):
    if summ[i] < 5000:
           summ[i] += randint(0, 10) * 1000
        
        
data['Сумма'] = summ

In [30]:
time = []
time_array = [12, 18, 24, 30, 36, 42, 48, 54, 60]

for i in range(Length):
    if summ[i] > 200000:
        time.append(time_array[randint(2, len(time_array) - 1)])
    else:
        time.append(time_array[randint(0, len(time_array)-2)])

        
for i in range(Length):
    if time[i] < 12:
           time[i] += randint(0, 10)
        
        
data['Срок'] = time

In [39]:
exp_array = [6 * i for i in range(80)]

exp_array[16]

96

In [41]:
exp = []
exp_array = [6 * i for i in range(50)]

for i in range(Length):
    if age[i] > 60:
        exp.append(exp_array[randint(30, len(exp_array) - 1)])
    elif age[i] <= 60 and age[i] > 40:
        exp.append(exp_array[randint(5, 45)])
    elif age[i] <= 40 and age[i] > 25:
        exp.append(exp_array[randint(5, 16)])
    else:
        exp.append(exp_array[randint(1, 10)])

        
for i in range(Length):
    if age[i] < 20 and exp[i] > 4:
           exp[i] -= exp_array[randint(1, 3)]
        
        
data['Опыт'] = exp

In [46]:
history = []

for i in range(Length):
    if y[i] == 1:
        history.append(fabs(round(normalvariate(3, 1))) )
    else:
        history.append(fabs(round(normalvariate(0, 1))))
        
        
data['Кредитная история'] = history

In [77]:
current = []

for i in range(Length):
    if y[i] == 1:
        current.append(fabs(floor(normalvariate(0, 0.01))))
    else:
        current.append(fabs(floor(normalvariate(0, 2))))
        
        
data['Текущие кредиты'] = current

In [49]:
overdue = []

for i in range(Length):
    if y[i] == 1:
        overdue.append(fabs(round(normalvariate(0, 0))) )
    else:
        overdue.append(fabs(round(normalvariate(0, 1))))
        
        
data['Непогашенные кредиты'] = overdue

In [78]:
data

,Итог,Зарплата,Возраст,Сумма,Срок,Опыт,Кредитная история,Текущие кредиты,Непогашенные кредиты
0,1,36000.0,32.0,276000.0,30,240,3.0,1.0,0.0
1,0,38000.0,35.0,631000.0,24,84,2.0,1.0,1.0
2,1,141000.0,61.0,645000.0,60,36,3.0,1.0,0.0
3,1,102000.0,24.0,442000.0,30,258,2.0,0.0,0.0
4,1,80000.0,51.0,182000.0,54,60,4.0,0.0,0.0
5,1,31000.0,39.0,208000.0,36,204,3.0,1.0,0.0
6,0,23000.0,24.0,531000.0,30,96,2.0,2.0,1.0
7,0,20000.0,36.0,571000.0,30,66,0.0,0.0,2.0
8,0,24000.0,18.0,478000.0,60,54,1.0,0.0,0.0
9,1,53000.0,34.0,198000.0,36,60,3.0,1.0,0.0
10,1,137000.0,55.0,425000.0,48,222,4.0,0.0,0.0
11,0,38000.0,31.0,557000.0,54,12,1.0,1.0,1.0
12,1,110000.0,40.0,522000.0,12,240,4.0,1.0,0.0
13,0,28000.0,49.0,489000.0,12,96,0.0,4.0,0.0
14,0,24000.0,24.0,602000.0,48,216,2.0,0.0,1.0
15,0,41000.0,26.0,428000.0,24,84,0.0,4.0,0.0
16,1,81000.0,39.0,232000.0,12,78,3.0,0.0,0.0
17,1,89000.0,46.0,241000.0,36,270,2.0,0.0,0.0
18,1,85000.0,50.0,203000.0,36,36,2.0,1.0,0.0
19,0,39000.0,47.0,350000.0,30,42,1.0,1.0,1.0
20,1,98000.0,47.0,231000.0,24,120,5.0,0.0,0.0
21,0,35000.0,50.0,659000.0,48,60,1.0,1.0,0.0
22,0,42000.0,29.0,417000.0,48,126,1.0,2.0,2.0
23,1,164000.0,47.0,493000.0,18,252,2.0,1.0,0.0
24,0,13000.0,26.0,443000.0,12,48,1.0,0.0,1.0
25,0,27000.0,18.0,498000.0,48,36,0.0,1.0,1.0
26,0,41000.0,23.0,518000.0,60,72,1.0,3.0,0.0
27,1,65000.0,51.0,253000.0,30,252,3.0,0.0,0.0
28,1,125000.0,54.0,451000.0,36,270,6.0,0.0,0.0
29,0,42000.0,24.0,433000.0,30,72,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...
9970,0,25000.0,34.0,737000.0,30,30,0.0,1.0,2.0
9971,0,10000.0,33.0,624000.0,36,90,0.0,1.0,0.0
9972,0,32000.0,29.0,593000.0,42,24,1.0,3.0,1.0
9973,0,27000.0,22.0,729000.0,54,66,1.0,0.0,0.0
9974,0,17000.0,55.0,449000.0,30,6,2.0,1.0,2.0
9975,1,102000.0,59.0,421000.0,48,60,2.0,1.0,0.0
9976,1,123000.0,68.0,605000.0,36,102,2.0,0.0,0.0
9977,1,267000.0,43.0,380000.0,36,102,3.0,0.0,0.0
9978,0,37000.0,36.0,539000.0,30,66,0.0,1.0,0.0
9979,1,98000.0,31.0,248000.0,60,36,2.0,1.0,0.0
9980,1,103000.0,35.0,523000.0,30,126,2.0,1.0,0.0
9981,1,93000.0,51.0,251000.0,42,84,2.0,0.0,0.0
9982,0,28000.0,40.0,491000.0,54,54,0.0,0.0,0.0
9983,1,202000.0,45.0,558000.0,48,36,4.0,1.0,0.0
9984,1,157000.0,34.0,653000.0,36,204,2.0,1.0,0.0
9985,0,38000.0,42.0,245000.0,48,84,1.0,2.0,1.0
9986,0,30000.0,18.0,504000.0,36,78,3.0,2.0,1.0
9987,0,24000.0,35.0,664000.0,36,24,1.0,1.0,1.0
9988,0,38000.0,44.0,548000.0,48,72,0.0,1.0,0.0
9989,0,15000.0,42.0,458000.0,42,60,2.0,0.0,1.0
9990,0,24000.0,24.0,298000.0,36,72,1.0,2.0,1.0
9991,0,29000.0,34.0,627000.0,42,66,0.0,0.0,0.0
9992,0,18000.0,18.0,466000.0,42,42,0.0,5.0,1.0
9993,0,25000.0,32.0,389000.0,42,54,2.0,1.0,0.0
9994,0,37000.0,19.0,474000.0,18,78,0.0,3.0,2.0
9995,0,15000.0,23.0,586000.0,54,36,0.0,3.0,0.0
9996,1,120000.0,35.0,499000.0,42,30,5.0,0.0,0.0
9997,1,41000.0,64.0,198000.0,42,192,3.0,0.0,0.0
9998,1,118000.0,39.0,469000.0,48,186,2.0,1.0,0.0
9999,1,31000.0,37.0,165000.0,48,30,2.0,0.0,0.0

In [79]:
data.to_csv('complete.csv', sep=',', header=False)

In [4]:
data = pd.read_csv('complete.csv', sep=',', header=None)

In [5]:
data.head()

   0  1         2     3         4   5    6    7    8    9
0  0  1   36000.0  32.0  276000.0  30  240  3.0  1.0  0.0
1  1  0   38000.0  35.0  631000.0  24   84  2.0  1.0  1.0
2  2  1  141000.0  61.0  645000.0  60   36  3.0  1.0  0.0
3  3  1  102000.0  24.0  442000.0  30  258  2.0  0.0  0.0
4  4  1   80000.0  51.0  182000.0  54   60  4.0  0.0  0.0